### ISSUE TITLE
Elimina Commenti

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/Caratteri#5]
Scrivere il codice corrispondente al diagramma degli stati

**Comment by Teodoro777** [comment]
Ho abbozzato un programma..

2015-12-14 18:47 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
A che serve conta_slash?

**Comment by Teodoro777** [comment]
A nulla, era rimasto da una vecchia bozza.

2015-12-14 19:32 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Gli stati sono mutuamente esclusivi ... se uno non è altro ...

**Comment by Teodoro777** [comment]
Allora non ho capito bene come fare a separare gli stati..

Il giorno 14 dicembre 2015 19:36, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Hai capito, solo che stai facendo lo stesso errore dei programmi precedenti sui caratteri.

**Comment by Teodoro777** [comment]
Ok quindi dove sbaglio? Il ragionamento mi sembra coerente con il
diagramma..

2015-12-14 19:40 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
:(( else if invece di if

**Comment by Teodoro777** [comment]
Wow così semplice?? Ahah già fatto..

2015-12-14 19:51 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ho fatto delle modifiche usando enum, vedi se ti è chiaro

il prossimo passo è tornare al diagramma degli stati e tener conto di possibili stringhe

**Comment by Teodoro777** [comment]
Tutto chiaro, ho visto su internet a cosa serve il costrutto enum

Il giorno 14 dicembre 2015 20:12, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Come capisco che sono in una stringa? La potrei rappresentare in diverse situazioni...

Inviato da iPad

**Comment by FabioZTessitore** [comment]
Le stringhe in C sono delimitate dalle virgolette doppie "
Il 15/dic/2015 02:39 PM, "Teodoro777" <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Ah già solo nelle virgolette possiamo trovare /*... Scusate la domanda
stupidissima.. :')

Il martedì 15 dicembre 2015, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Ma che stai dicendo?
In ogni stato la gestione delle stringhe cambia
Il 15/dic/2015 07:12 PM, "Teodoro777" <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Si si lo so..

Il martedì 15 dicembre 2015, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by Teodoro777** [comment]
Ho caricato un aggiornamento del diagramma, non so perchè ma nel pull mi
era uscito un merge, poi quando ho fatto il pull lo ha messo in automatico
come commit..

Il giorno 15 dicembre 2015 19:23, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
forse avevi fatto delle modifiche che non avevi inviato

**Comment by FabioZTessitore** [comment]
il disegno che hai fatto va fuori pagina e non si visualizza

**Comment by Teodoro777** [comment]
L'ho fatto così perchè è troppa roba, se aprite con inkscape dovreste
vedere tutto

2015-12-16 15:18 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ho aggiornato il diagramma

**Comment by Teodoro777** [comment]
Deve spampare altri caratteri nella stringa.

2015-12-16 15:25 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
eh, completa lo schema, poi metti mano al codice e dimmi se trovi difficoltà a fare le modifiche

**Comment by Teodoro777** [comment]
Perchè non è completo lo schema?

2015-12-16 15:48 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
no, non si capisce cosa succede quando arrivano caratteri nello stato stringa

**Comment by Teodoro777** [comment]
Ho completato il programma, credo di aver capito bene l'utilità degli stati
;)

2015-12-16 16:22 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
bene, però il diagramma continua a non essere aggiornato.

ps. quando scrivi o confronti il carattere " è meglio fare #'\"'#

**Comment by Teodoro777** [comment]
Ok dopo aggiusto pure il diagramma, passiamo al prossimo?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
haha

in teoria dovresti considerare che puoi trovare le virgolette negli apici
'\"' e questo non apre una stringa

cmq piu' tardi ti faccio sapere cosa fare

Il giorno 16 dicembre 2015 17:18, Teodoro777 <notifications@github.com> ha
scritto:

**Comment by Teodoro777** [comment]
Non apre una stringa ma comunque lo stampa regolarmente come dovrebbe

Inviato da iPad

**Comment by FabioZTessitore** [comment]
eh no, quando trova una " entra nello stato stringa. da quel momento in poi è tutto stringa, pure i commenti, finché non trova un'altra "
ti trovi?

**Comment by Teodoro777** [comment]
Ahh già!!! Ovvio, non avevo letto bene il mex di prima

Il mercoledì 16 dicembre 2015, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by Teodoro777** [comment]
Ho aggiustato il diagramma. Ma anche '*' è meglio mettere '\*' ?

Il giorno 16 dicembre 2015 18:10, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
no, asterisco non comporta nessuna ambiguità

Il giorno 17 dicembre 2015 19:09, Teodoro777 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ok, il diagramma va bene per le stringhe.
bisogna aggiungere lo stato apici

**Comment by Teodoro777** [comment]
Ok ora lo faccio


2015-12-17 19:12 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Teodoro777** [comment]
Ma comunque quel cloud9 ide è a pagamento?

Il giorno 17 dicembre 2015 19:15, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
è free con una configurazione di base, se poi si richiedono più risorse si
pagano

Il giorno 17 dicembre 2015 19:16, Teodoro777 <notifications@github.com> ha
scritto:

**Comment by Teodoro777** [comment]
Ho caricato il codice con gli apici, aggiorno velocemente il diagramma..

Il giorno 17 dicembre 2015 19:19, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
penso tu abbia capito bene il meccanismo.

In teoria ci sarebbe da fare una modifica perché il programma non supera la prova di una
```C
putchar('\''); /* il secondo apice non chiude! il terzo si! */
```

per me possiamo chiudere e andare avanti. dimmi tu che ne pensi

**Comment by Teodoro777** [comment]
Si sì ormai queste cose le ho capite, andiamo avanti. Comunque aggiusterò il codice. 

Inviato da iPad
