### ISSUE TITLE
ordine degli if

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/Caratteri#6]
non sono convinto che funzioni la modifica al codice.
Quando arriva un asterisco il primo if chiede se il carattere è diverso da '/' e tale condizione è chiaramente vera.
Prova a modificare il file di test mettendo una chiusura di commento con due soli asterischi. Es
```c
/* commento da testare **/
```

**Comment by Teodoro777** [comment]
Non ho ben capito perché modificando l'ordine degli if si è aggiustato il programma..

Inviato da iPad

**Comment by FabioZTessitore** [comment]
Te l'ho spiegato nel post precedente. Il primo if chiedeva se il carattere era diverso da /. In questa condizione ricade anche *. Quindi la condizione successiva (se il carattere è uguale ad *) non veniva mai raggiunta.

**Comment by Teodoro777** [comment]
Ahh giusto

Il giorno 9 gennaio 2016 13:06, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
ok, giusto per completezza, la riga 57 a questo punto può diventare un else (senza condizione)
